version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./backend/:/var/www/html/
    ports:
      - "8100:80"
    environment:
      mongohost: '@ds139722.mlab.com:39722/'
      username:
      password:
      database: studios
    stdin_open: true
    tty: true
  app:
    image: hitalos/laravel:latest
    ports:
      - 80:80
    environment:
      ENDPOINT: http://web/search
      RADIUSSEARCH: http://web/searchlocation
    volumes:
      - ./client:/var/www