<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'customservice' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/CustomService.php';

return $this->services['customservice'] = new \App\Service\CustomService($this->getEnv('mongohost'), $this->getEnv('username'), $this->getEnv('password'), $this->getEnv('database'));
